apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-flask
spec:
  template:
    spec:
      containers:
      - image: tomershor199/py-flask
---
apiVersion: v1
kind: Service
metadata:
  name: py-flask
spec:
  ports:
  - port: 8000
    targetPort: 8020