apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-service
spec:
  template:
    spec:
      containers:
      - image: tomershor199/go-service
---
apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  ports:
  - port: 8000
    targetPort: 8010